export const CREDENTIAL_ENV =
  /^(TURSO_|AIRTABLE_|RESEND_|PRISMIC_|NETLIFY_|DISCORD_|GA_|PERPLEXITY_|TURNSTILE_|FORMS_INGEST_|PROSPECT_|DASHBOARD_|OPERATOR_EMAIL$|REPORT_BASE_URL$|GH_TOKEN$|GITHUB_TOKEN$|CLAUDE_OAUTH$)/;
