import type { ThemeIR } from "../ir.js";

/** ThemeIR → a Tailwind v4 `@theme` block of CSS custom properties. Deterministic.
 *  A leading comment lists the exact web-font weights the export loads, so the
 *  design pass can install them without measuring the rendered site. */
export function emitThemeCss(theme: ThemeIR): string {
  const lines: string[] = [];
  if (theme.fontLoad.length) {
    const spec = theme.fontLoad.map((f) => `${f.family} ${f.weights.join(",")}`).join("; ");
    lines.push(`/* Fonts to load — ${spec} */`);
  }
  lines.push("@theme {");
  for (const c of theme.colors) lines.push(`  --color-${c.role}: ${c.value};`);
  lines.push(`  --font-heading: ${theme.fonts.heading || "sans-serif"};`);
  lines.push(`  --font-body: ${theme.fonts.body || "sans-serif"};`);
  for (const t of theme.textStyles) {
    if (t.label) lines.push(`  /* ${t.role} — ${t.label} */`);
    lines.push(`  --text-${t.role}: ${t.size};`);
    lines.push(`  --text-${t.role}--line-height: ${t.lineHeight};`);
    lines.push(`  --text-${t.role}--font-weight: ${t.weight};`);
    if (t.fontFamily) lines.push(`  --text-${t.role}--font-family: ${t.fontFamily};`);
    if (t.transform) lines.push(`  --text-${t.role}--text-transform: ${t.transform};`);
    if (t.letterSpacing) lines.push(`  --text-${t.role}--letter-spacing: ${t.letterSpacing};`);
    if (t.mobileSize) lines.push(`  --text-${t.role}--mobile-font-size: ${t.mobileSize};`);
    if (t.mobileLineHeight)
      lines.push(`  --text-${t.role}--mobile-line-height: ${t.mobileLineHeight};`);
  }
  lines.push("}");
  return lines.join("\n") + "\n";
}

/** ThemeIR → the `.txt-role-textN` utility layer: one rule per text style that
 * maps the role's `@theme` vars (emitted by {@link emitThemeCss}) onto the
 * h1–h6/p it wraps. A slice applies `txt-role-textN` to a block and its
 * headings/paragraphs pick up that role's type — the same mechanism the
 * per-site `gen-blux-theme.mjs` script used to hand-generate, now owned by
 * `blux emit` so a converted site consumes it with zero hand-tuning.
 *
 * The utility references every var unconditionally; when a role omits an
 * optional one (letter-spacing, text-transform, font-family) the `var(…, …)`
 * fallback resolves to a safe default, so the rule is inert for that property.
 * Returns "" when the theme has no text styles. */
export function emitRolesCss(theme: ThemeIR): string {
  if (!theme.textStyles.length) return "";
  const lines: string[] = [
    "/* Role utilities — one .txt-role-textN per Blux text style, mapping its",
    "   @theme vars onto the heading/paragraph it wraps. Generated by blux emit. */",
  ];
  for (const t of theme.textStyles) {
    const r = t.role;
    lines.push(
      `.txt-role-${r} :is(h1, h2, h3, h4, h5, h6, p) {`,
      `  font-family: var(--text-${r}--font-family, var(--font-heading));`,
      `  font-size: var(--text-${r});`,
      `  font-weight: var(--text-${r}--font-weight);`,
      `  line-height: var(--text-${r}--line-height);`,
      `  letter-spacing: var(--text-${r}--letter-spacing, normal);`,
      `  text-transform: var(--text-${r}--text-transform, none);`,
      `  margin: 0;`,
      `}`,
    );
  }
  return lines.join("\n") + "\n";
}
