import type { ConfigName } from "../../types.js";

export type ConfigTemplate = {
  config: ConfigName;
  path: string;
  contents: string;
};

const eslint: ConfigTemplate = {
  config: "eslint",
  path: "eslint.config.js",
  contents: `import { createEslintConfig } from "@reddoorla/maintenance/configs/eslint";
import svelteConfig from "./svelte.config.js";

export default createEslintConfig({ svelteConfig });
`,
};

const prettier: ConfigTemplate = {
  config: "prettier",
  path: ".prettierrc.json",
  contents: `{
  "trailingComma": "all",
  "singleQuote": false,
  "printWidth": 100,
  "plugins": ["prettier-plugin-svelte"]
}
`,
};

const prettierIgnore: ConfigTemplate = {
  config: "prettier-ignore",
  path: ".prettierignore",
  contents: `pnpm-lock.yaml
.svelte-kit/
build/
.netlify/
dist/
`,
};

const lighthouse: ConfigTemplate = {
  config: "lighthouse",
  path: "lighthouserc.json",
  contents: `${JSON.stringify(
    {
      $note:
        "Generated by @reddoorla/maintenance sync-configs; edit src/configs/lighthouse.ts in the package instead.",
      extends: "@reddoorla/maintenance/configs/lighthouse",
    },
    null,
    2,
  )}
`,
};

const playwrightA11y: ConfigTemplate = {
  config: "playwright-a11y",
  path: "playwright.config.ts",
  contents: `export { default } from "@reddoorla/maintenance/configs/playwright-a11y";
`,
};

const svelte: ConfigTemplate = {
  config: "svelte",
  path: "svelte.config.js",
  contents: `import { createSvelteConfig } from "@reddoorla/maintenance/configs/svelte";
import adapter from "@sveltejs/adapter-netlify";

/** @type {import('@sveltejs/kit').Config} */
export default createSvelteConfig({
  kit: { adapter: adapter({ edge: false, split: false }) },
});
`,
};

// The `ci:` job name below + the reusable workflow's `ci` job name produce the
// branch-protection check context "ci / ci" — kept in sync with REQUIRED_CHECK in
// src/recipes/self-updating/index.ts. Renaming this job means updating that constant.
const ci: ConfigTemplate = {
  config: "ci",
  path: ".github/workflows/ci.yml",
  contents: `name: ci
on:
  pull_request:
  push:
    branches: [main]
jobs:
  ci:
    uses: reddoorla/.github/.github/workflows/ci.yml@78c4da64b675f0f474961f12715f2a4c09d46eb5 # v1.0.0
`,
};

const renovateAction: ConfigTemplate = {
  config: "renovate-action",
  path: ".github/workflows/renovate.yml",
  contents: `name: renovate
on:
  schedule:
    - cron: "0 7 * * 1"
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: renovatebot/github-action@v46.1.14
        with:
          token: \${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_REPOSITORIES: \${{ github.repository }}
`,
};

const renovateConfig: ConfigTemplate = {
  config: "renovate-config",
  path: "renovate.json",
  contents: `{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": ["github>reddoorla/.github:renovate-config"]
}
`,
};

const netlify: ConfigTemplate = {
  config: "netlify",
  path: "netlify.toml",
  contents: `[build]
    command = "pnpm build"
    publish = "build/"
    functions = "functions/"

[build.environment]
    NODE_VERSION = "22"
    COREPACK_INTEGRITY_KEYS = "0"

# Baseline security headers for all responses. CSP is emitted per-response by
# SvelteKit (see \`kit.csp\` in svelte.config.js) so it is intentionally omitted
# here to avoid conflicting duplicates.
[[headers]]
    for = "/*"
    [headers.values]
        Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
        X-Content-Type-Options = "nosniff"
        X-Frame-Options = "SAMEORIGIN"
        Referrer-Policy = "strict-origin-when-cross-origin"
        Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
        Cross-Origin-Opener-Policy = "same-origin"

[[headers]]
    for = "/favicon.png"
    [headers.values]
        Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
    for = "/_app/immutable/*"
    [headers.values]
        Cache-Control = "public, max-age=31536000, immutable"
`,
};

export const ALL_TEMPLATES: ConfigTemplate[] = [
  eslint,
  prettier,
  prettierIgnore,
  lighthouse,
  playwrightA11y,
  svelte,
  ci,
  renovateAction,
  renovateConfig,
  netlify,
];

export function templatesByName(which: ConfigName[]): ConfigTemplate[] {
  return ALL_TEMPLATES.filter((t) => which.includes(t.config));
}
