#!/usr/bin/env -S pnpm tsx
import { execFileSync } from "node:child_process";
import { realpathSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { BLOCKED_EMAIL_DOMAINS } from "../src/forms/spam-classifier.js";

export const REPO = "disposable-email-domains/disposable-email-domains";
export const FILE = "disposable_email_blocklist.conf";
export const MIN_COUNT = 5000;
const DOMAIN_RE = /^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$/;
const USAGE = "usage: pnpm tsx scripts/refresh-disposable-domains.mts [--ref <commit sha>]";

export type Snapshot = { domains: string[]; excluded: string[] };

export function parseBlocklist(text: string, blocked: readonly string[]): Snapshot {
  const seen = new Set<string>();
  for (const [i, raw] of text.split("\n").entries()) {
    const line = raw.trim();
    if (line === "" || line.startsWith("#")) continue;
    if (!DOMAIN_RE.test(line))
      throw new Error(`line ${i + 1} is not a bare lowercase domain: ${line}`);
    seen.add(line);
  }
  const excluded = [...seen].filter((d) => blocked.includes(d)).sort();
  const domains = [...seen].filter((d) => !blocked.includes(d)).sort();
  if (domains.length < MIN_COUNT)
    throw new Error(
      `only ${domains.length} domains, under the ${MIN_COUNT} floor: a truncated fetch?`,
    );
  return { domains, excluded };
}

export function renderSnapshot(domains: readonly string[], commit: string): string {
  if (!/^[0-9a-f]{40}$/.test(commit)) throw new Error(`not a full commit sha: ${commit}`);
  return `// Generated by scripts/refresh-disposable-domains.mts. Do not edit by hand.
//
// Source: https://github.com/${REPO}/blob/${commit}/${FILE}
// Licence: CC0 1.0 Universal (public domain dedication), so no attribution is required.
//
// These are throwaway-mailbox providers. They feed the corroborated +45
// disposable-email signal only, and must never be copied into
// BLOCKED_EMAIL_DOMAINS, which buckets a submission on its own.

export const VENDORED_DISPOSABLE_SOURCE = {
  repo: "${REPO}",
  commit: "${commit}",
  licence: "CC0-1.0",
  count: ${domains.length},
} as const;

export const VENDORED_DISPOSABLE_DOMAINS: ReadonlySet<string> = new Set(
  \`
${domains.join("\n")}
\`
    .split("\\n")
    .filter((d) => d !== ""),
);
`;
}

function resolveRef(ref: string | undefined): string {
  if (ref !== undefined) return ref;
  const out = execFileSync("git", ["ls-remote", `https://github.com/${REPO}`, "refs/heads/main"], {
    encoding: "utf8",
  });
  const sha = out.split(/\s/)[0] ?? "";
  if (!/^[0-9a-f]{40}$/.test(sha)) throw new Error(`could not resolve ${REPO} main: ${out}`);
  return sha;
}

async function main(): Promise<void> {
  const argv = process.argv.slice(2);
  let ref: string | undefined;
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === "--ref" && argv[i + 1] !== undefined) ref = argv[++i];
    else throw new Error(USAGE);
  }
  const commit = resolveRef(ref);
  const url = `https://raw.githubusercontent.com/${REPO}/${commit}/${FILE}`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${url} answered ${res.status}`);
  const { domains, excluded } = parseBlocklist(await res.text(), BLOCKED_EMAIL_DOMAINS);
  const out = join(
    dirname(fileURLToPath(import.meta.url)),
    "..",
    "src/forms/disposable-domains.snapshot.ts",
  );
  writeFileSync(out, renderSnapshot(domains, commit));
  process.stdout.write(`wrote ${domains.length} domains from ${REPO}@${commit}\n`);
  if (excluded.length > 0)
    process.stdout.write(`left out, already blocked: ${excluded.join(", ")}\n`);
}

const self = (p: string): string => {
  try {
    return realpathSync(p);
  } catch {
    return p;
  }
};
if (process.argv[1] && self(process.argv[1]) === self(fileURLToPath(import.meta.url))) {
  main().catch((e: unknown) => {
    process.stderr.write(
      `refresh-disposable-domains: ${e instanceof Error ? e.message : String(e)}\n`,
    );
    process.exitCode = 1;
  });
}
