import { writeFile } from "node:fs/promises";
import { join } from "node:path";

export type SummaryInput = {
  cwd: string;
  filesChangedByCodemods: number;
  svelteMigrateRan: boolean;
  tailwindUpgraded: boolean;
};

export async function writeMigrationSummary(input: SummaryInput): Promise<string> {
  const lines = [
    `# Svelte 4 → 5 migration summary`,
    ``,
    `Generated by @reddoorla/maintenance.`,
    ``,
    `- svelte-migrate run: ${input.svelteMigrateRan ? "yes" : "no"}`,
    `- @tailwindcss/upgrade run: ${input.tailwindUpgraded ? "yes" : "no"}`,
    `- .svelte files touched by gotcha codemods: ${input.filesChangedByCodemods}`,
    ``,
    `Next steps:`,
    `- Run \`pnpm run check\` and resolve any remaining warnings.`,
    `- Spot-check rune migrations in components that use \`reactive\` statements.`,
    `- Verify Playwright a11y tests still pass.`,
  ];
  const content = lines.join("\n") + "\n";
  const path = join(input.cwd, "MIGRATION_SVELTE_5.md");
  await writeFile(path, content, "utf-8");
  return path;
}
